# verify: job var > pipeline var, job var > dialog var, job var > repo var, job var > project var
# verify pipeline var > dialog var, pipeline var > repo var, pipeline var > project var
variables:
  TEST: "This is pipeline var"

stages:
  - stage1
  - stage2

job 1:
  stage: stage1
  variables:
    TEST: "This is job var"
  commands:
    - echo $TEST

job 2:
  stage: stage1
  commands:
    - echo $TEST