# verify only with variables
variables:
  pipeline_var: "This is pipeline var"

stages:
  - stage1
  - stage2

job 1:
  stage: stage1
  only:
    variables:
      - $job_var
  variables:
    job_var: "This a job var"
  commands:
    - echo "job 1"

job 2:
  stage: stage1
  only:
    variables:
      - $job_var
      - $pipeline_var
  commands:
    - echo "job 2"

job 3:
  stage: stage1
  only:
    variables:
      - $job_var
      - $dialog_var
  commands:
    - echo "job 3"

job 4:
  stage: stage1
  only:
    variables:
      - $job_var
      - $repo_var
  commands:
    - echo "job 4"

job 5:
  stage: stage1
  only:
    variables:
      - $job_var
      - $project_var
  commands:
    - echo "job 5"

job 6:
  stage: stage2
  commands:
    - echo "job 6"
